version: 2

updates:
    -   package-ecosystem: "composer"
        directory: /
        schedule:
            interval: "weekly"
            day: "tuesday"
            time: "06:00"
            timezone: "Etc/UTC"
        groups:
            prod-dependencies:
                dependency-type: "production"
                update-types:
                    - "minor"
                    - "patch"
            dev-dependencies:
                dependency-type: "development"
                update-types:
                    - "major"
                    - "minor"
                    - "patch"
        commit-message:
            prefix: "Composer"
            include: "scope"
        labels:
            - "dependabot"
        assignees:
            - "mitopp"
        open-pull-requests-limit: 10
        versioning-strategy: "lockfile-only"

    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "weekly"
